// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRcvL3WYCIr8oR6_PrWJdWMZ5GqW9qSYY',
    appId: '1:490594493494:web:0f51d663fc0a6fab99a497',
    messagingSenderId: '490594493494',
    projectId: 'notes-app-beginner-project',
    authDomain: 'notes-app-beginner-project.firebaseapp.com',
    storageBucket: 'notes-app-beginner-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhds0zzEC1LmApX37HDKc1hER8ZwLHH9A',
    appId: '1:490594493494:android:1bd3679550d877fa99a497',
    messagingSenderId: '490594493494',
    projectId: 'notes-app-beginner-project',
    storageBucket: 'notes-app-beginner-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_oWByZlxML1Ez9Yd8oHE8M9sq7eAU-uI',
    appId: '1:490594493494:ios:f2d927342607dd2e99a497',
    messagingSenderId: '490594493494',
    projectId: 'notes-app-beginner-project',
    storageBucket: 'notes-app-beginner-project.appspot.com',
    iosClientId: '490594493494-7gufol2qmfgfdhklmeslqrps8f3g8l6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_oWByZlxML1Ez9Yd8oHE8M9sq7eAU-uI',
    appId: '1:490594493494:ios:f2d927342607dd2e99a497',
    messagingSenderId: '490594493494',
    projectId: 'notes-app-beginner-project',
    storageBucket: 'notes-app-beginner-project.appspot.com',
    iosClientId: '490594493494-7gufol2qmfgfdhklmeslqrps8f3g8l6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningProject',
  );
}
